/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { KeyResultService } from "../keyResult.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { KeyResultCreateInput } from "./KeyResultCreateInput";
import { KeyResult } from "./KeyResult";
import { KeyResultFindManyArgs } from "./KeyResultFindManyArgs";
import { KeyResultWhereUniqueInput } from "./KeyResultWhereUniqueInput";
import { KeyResultUpdateInput } from "./KeyResultUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class KeyResultControllerBase {
  constructor(
    protected readonly service: KeyResultService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: KeyResult })
  @nestAccessControl.UseRoles({
    resource: "KeyResult",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createKeyResult(
    @common.Body() data: KeyResultCreateInput
  ): Promise<KeyResult> {
    return await this.service.createKeyResult({
      data: {
        ...data,

        objective: data.objective
          ? {
              connect: data.objective,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        createdBy: true,
        description: true,
        dueDate: true,
        id: true,

        objective: {
          select: {
            id: true,
          },
        },

        status: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [KeyResult] })
  @ApiNestedQuery(KeyResultFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "KeyResult",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async keyResults(@common.Req() request: Request): Promise<KeyResult[]> {
    const args = plainToClass(KeyResultFindManyArgs, request.query);
    return this.service.keyResults({
      ...args,
      select: {
        createdAt: true,
        createdBy: true,
        description: true,
        dueDate: true,
        id: true,

        objective: {
          select: {
            id: true,
          },
        },

        status: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: KeyResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyResult",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async keyResult(
    @common.Param() params: KeyResultWhereUniqueInput
  ): Promise<KeyResult | null> {
    const result = await this.service.keyResult({
      where: params,
      select: {
        createdAt: true,
        createdBy: true,
        description: true,
        dueDate: true,
        id: true,

        objective: {
          select: {
            id: true,
          },
        },

        status: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: KeyResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyResult",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateKeyResult(
    @common.Param() params: KeyResultWhereUniqueInput,
    @common.Body() data: KeyResultUpdateInput
  ): Promise<KeyResult | null> {
    try {
      return await this.service.updateKeyResult({
        where: params,
        data: {
          ...data,

          objective: data.objective
            ? {
                connect: data.objective,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          createdBy: true,
          description: true,
          dueDate: true,
          id: true,

          objective: {
            select: {
              id: true,
            },
          },

          status: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: KeyResult })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "KeyResult",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteKeyResult(
    @common.Param() params: KeyResultWhereUniqueInput
  ): Promise<KeyResult | null> {
    try {
      return await this.service.deleteKeyResult({
        where: params,
        select: {
          createdAt: true,
          createdBy: true,
          description: true,
          dueDate: true,
          id: true,

          objective: {
            select: {
              id: true,
            },
          },

          status: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
